### ISSUE TITLE
laravel 9 support

### ISSUE THREAD

**Issue by josiahke** [godruoyi/laravel-tabler-ui#1]
hello,

is there plans for laravel 9 support

**Comment by godruoyi** [comment]
Thanks for your interest in this, I will support laravel9 tomorrow, if everything is ok.

**Comment by godruoyi** [comment]
I think Laravel9 is now supported, see this [commit](https://github.com/godruoyi/laravel-tabler-ui/commit/dbacb4807a1d52fc9b9576278e4771d6f0d6b317) and if you have any questions, let me know.

**Comment by josiahke** [comment]
thank you for the quick response. was able to install
